"""Tools for transparent x-ray reflectivity calculations."""

from .constants import HC_EV_ANGSTROM
from .fields import (
    FieldProfile,
    depth_grid,
    effective_layers_with_roughness,
    electric_field_profile,
    layer_field_amplitudes,
    parratt_reflection_amplitudes,
    transfer_matrix_electric_field_profile,
    transfer_matrix_field_amplitudes,
    transfer_matrix_reflectivity,
    transfer_matrix_reflection_amplitude,
)
from .imfp import IMFPTable, imfp_from_file, imfp_path, load_imfp
from .layers import Layer, refractive_index, vacuum
from .optical_constants import (
    OpticalConstantsTable,
    constants_from_file,
    layer_from_file,
    load_optical_constants,
    optical_constants_path,
)
from .profiles import (
    StackProfiles,
    sample_concentration_profiles,
    sample_stack_property,
    stack_depth_grid,
)
from .reflectivity import (
    apply_roughness,
    energy_to_wavelength,
    fresnel_r_s,
    kz_in_layers,
    parratt_amplitude,
    parratt_reflectivity,
)
from .simulation import (
    CoreLevelRequest,
    CoreLevelResult,
    ReflectivityRequest,
    ReflectivityResult,
    RockingCurveRequest,
    RockingCurveResult,
    SimulationStack,
    StackLayer,
    simulate_reflectivity,
    simulate_rocking_curve,
    simulate_rocking_curves,
    stack_from_layers,
)
from .xps import (
    RockingCurve,
    attenuation_factor,
    graded_layer_property_at_depth,
    integrate_xps_intensity,
    nominal_layer_index_at_depth,
    normalized_rocking_curve,
)

__all__ = [
    "HC_EV_ANGSTROM",
    "CoreLevelRequest",
    "CoreLevelResult",
    "FieldProfile",
    "IMFPTable",
    "Layer",
    "OpticalConstantsTable",
    "ReflectivityRequest",
    "ReflectivityResult",
    "RockingCurve",
    "RockingCurveRequest",
    "RockingCurveResult",
    "SimulationStack",
    "StackProfiles",
    "StackLayer",
    "apply_roughness",
    "constants_from_file",
    "depth_grid",
    "effective_layers_with_roughness",
    "electric_field_profile",
    "energy_to_wavelength",
    "fresnel_r_s",
    "graded_layer_property_at_depth",
    "attenuation_factor",
    "imfp_from_file",
    "imfp_path",
    "integrate_xps_intensity",
    "kz_in_layers",
    "layer_field_amplitudes",
    "layer_from_file",
    "load_optical_constants",
    "load_imfp",
    "nominal_layer_index_at_depth",
    "normalized_rocking_curve",
    "optical_constants_path",
    "parratt_amplitude",
    "parratt_reflection_amplitudes",
    "parratt_reflectivity",
    "refractive_index",
    "sample_concentration_profiles",
    "sample_stack_property",
    "simulate_reflectivity",
    "simulate_rocking_curve",
    "simulate_rocking_curves",
    "stack_from_layers",
    "stack_depth_grid",
    "transfer_matrix_electric_field_profile",
    "transfer_matrix_field_amplitudes",
    "transfer_matrix_reflectivity",
    "transfer_matrix_reflection_amplitude",
    "vacuum",
]
